/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartContractVehicle
 * OpenAPI spec version: 1.0
 */

export interface Address {
  id?: number;
  /**
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  extraInfo?: string | null;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  floor?: string | null;
  houseNumber: number;
  /**
   * @minLength 0
   * @maxLength 50
   */
  street: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  city: string;
  /**
   * @minLength 0
   * @maxLength 15
   */
  postalCode: string;
  /**
   * @minLength 0
   * @maxLength 110
   */
  country: string;
}
