/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartContractVehicle
 * OpenAPI spec version: 1.0
 */
import type { Address } from './address';

export interface User {
  id?: number;
  /** @minLength 1 */
  lastName: string;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  email: string;
  birthday: string;
  billing: Address;
  mailing: Address;
  /** @minLength 1 */
  password: string;
  /** @nullable */
  phoneNumber?: string | null;
  /** @minLength 1 */
  walletId: string;
}
