version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: smart_contract_vehicle_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart_contract_vehicle_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
