version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: smart_contract_vehicle_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart_contract_vehicle_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache_local
    ports:
      - "7545:7545"
    command:
      [
        "--port", "7545",
        "--networkId", "5777",
        "--accounts", "10",
        "--defaultBalanceEther", "100"
      ]
    restart: unless-stopped

volumes:
  pgdata:
